spring:
  config:
    import: optional:file:.env[.properties]
  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    bootstrap-servers: localhost:9092
server:
  port: 8082
grpc:
  client:
    GLOBAL:
      address: ${GRPC_HOST}
      negotiation-type: plaintext
push:
  batch-size: ${BATCH_SIZE}